// WhyThisClient — reusable reasoning panel for WealthLens intelligence signals.
//
// Accepts:
//   signal  — an intelligence signal object from src/data/intelligence.js
//   client  — a client object from src/data/clients.js
//
// Renders a visual explanation of WHY a signal is relevant to a specific client,
// walking through: Market Event → Portfolio Exposure → Risk Profile → Goals →
// Liquidity Needs → Urgency → Client Relevance Score.
//
// The four factor scores are PROTOTYPE values for demonstration purposes.
// They are not generated by a real AI model. The RM remains the decision-maker.

import {
  Zap,
  PieChart,
  Shield,
  Target,
  Wallet,
  Clock,
  ChevronDown,
} from 'lucide-react'
import { Card, Confidence } from './ui.jsx'
import { formatChf } from '../utils/format.js'

// ---------------------------------------------------------------------------
// Prototype relevance factor scores.
// Static mock values — illustrate how portfolio exposure, market context and
// client objectives could be weighted to help an RM prioritise attention.
// ---------------------------------------------------------------------------
const RELEVANCE_FACTORS = [
  { label: 'Portfolio Exposure', score: 91 },
  { label: 'Market Impact',      score: 82 },
  { label: 'Goal Sensitivity',   score: 94 },
  { label: 'Urgency',            score: 88 },
]

// Priority → human-readable urgency string
const PRIORITY_LABEL = { high: 'High — act this month', medium: 'Medium — monitor closely', low: 'Low — review next cycle' }

// Priority → semantic colour variable
const PRIORITY_COLOR = { high: 'var(--danger)', medium: 'var(--warn)', low: 'var(--ok)' }

export default function WhyThisClient({ signal, client }) {
  if (!signal || !client) return null

  // Derive the most relevant portfolio-exposure signal item (first entry).
  const exposureNote = signal.signals?.[0] ?? null

  // Derive the liquidity-related objective if one exists.
  const liquidityObjective = client.objectives?.find(
    (o) => /liquid|s\$|cash|requirement/i.test(o)
  ) ?? null

  const relevancePct = Math.round((signal.confidence ?? 0) * 100)

  return (
    <Card>
      <div className="card-head">
        <h3 className="serif" style={{ fontSize: 17 }}>Why this client?</h3>
        <span className="eyebrow" style={{ letterSpacing: '0.1em' }}>Reasoning flow</span>
      </div>

      <div className="card-pad" style={{ paddingTop: 20 }}>

        {/* ── Reasoning chain ─────────────────────────────────────── */}
        <div style={{ marginBottom: 28 }}>
          <ReasoningStep
            icon={<Zap size={15} strokeWidth={2} />}
            label="Market event"
            value={signal.trigger}
          />
          <StepConnector />

          <ReasoningStep
            icon={<PieChart size={15} strokeWidth={2} />}
            label="Portfolio exposure"
            value={exposureNote ?? 'See portfolio allocation.'}
          />
          <StepConnector />

          <ReasoningStep
            icon={<Shield size={15} strokeWidth={2} />}
            label="Client risk profile"
            value={client.riskProfile}
            chip
          />
          <StepConnector />

          <ReasoningStep
            icon={<Target size={15} strokeWidth={2} />}
            label="Financial goals"
            value={null}
          >
            <ul style={{ margin: '6px 0 0', padding: 0, listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 5 }}>
              {client.objectives.map((o) => (
                <li key={o} style={{ display: 'flex', gap: 8, fontSize: 13.5, color: 'var(--ink-soft)', alignItems: 'flex-start' }}>
                  <span style={{ width: 6, height: 6, borderRadius: '50%', background: 'var(--gold-soft)', flexShrink: 0, marginTop: 6 }} />
                  {o}
                </li>
              ))}
            </ul>
          </ReasoningStep>
          <StepConnector />

          <ReasoningStep
            icon={<Wallet size={15} strokeWidth={2} />}
            label="Liquidity needs"
            value={null}
          >
            <div style={{ marginTop: 6, display: 'flex', flexDirection: 'column', gap: 4 }}>
              <span style={{ fontSize: 13.5, color: 'var(--ink-soft)' }}>
                Available liquidity: <strong style={{ color: 'var(--ink)', fontWeight: 600 }}>{formatChf(client.liquidityChf)}</strong>
              </span>
              {liquidityObjective && (
                <span style={{ fontSize: 13.5, color: 'var(--ink-soft)' }}>
                  Requirement: <strong style={{ color: 'var(--ink)', fontWeight: 600 }}>{liquidityObjective}</strong>
                </span>
              )}
            </div>
          </ReasoningStep>
          <StepConnector />

          <ReasoningStep
            icon={<Clock size={15} strokeWidth={2} />}
            label="Urgency"
            value={null}
          >
            <div style={{ marginTop: 6, display: 'flex', alignItems: 'center', gap: 10, flexWrap: 'wrap' }}>
              <span style={{
                fontSize: 12.5,
                fontWeight: 600,
                color: PRIORITY_COLOR[signal.priority] ?? 'var(--ink)',
                background: 'var(--surface-2)',
                border: `1px solid ${PRIORITY_COLOR[signal.priority] ?? 'var(--line)'}`,
                borderRadius: 30,
                padding: '3px 10px',
              }}>
                {PRIORITY_LABEL[signal.priority] ?? signal.priority}
              </span>
              <span style={{ fontSize: 13, color: 'var(--ink-muted)' }}>Horizon: {signal.horizon}</span>
            </div>
          </ReasoningStep>
        </div>

        {/* ── Relevance score ─────────────────────────────────────── */}
        <div style={{
          background: 'linear-gradient(160deg, var(--primary) 0%, #123647 100%)',
          borderRadius: 'var(--radius-sm)',
          padding: '20px 22px',
          marginBottom: 24,
          display: 'flex',
          alignItems: 'center',
          gap: 24,
          flexWrap: 'wrap',
        }}>
          <div>
            <div style={{ fontSize: 11, letterSpacing: '0.14em', textTransform: 'uppercase', color: 'rgba(200,162,74,0.85)', fontWeight: 600, marginBottom: 6 }}>
              Client relevance score
            </div>
            <div style={{ fontFamily: 'var(--font-serif)', fontSize: 48, fontWeight: 600, color: '#fff', lineHeight: 1, letterSpacing: '-0.03em' }}>
              {relevancePct}
            </div>
            <div style={{ fontSize: 12, color: 'rgba(234,240,242,0.55)', marginTop: 4 }}>
              out of 100
            </div>
          </div>
          <div style={{ flex: 1, minWidth: 160 }}>
            <div style={{ marginBottom: 8 }}>
              <Confidence value={signal.confidence} />
            </div>
            <p style={{ margin: 0, fontSize: 12, color: 'rgba(234,240,242,0.65)', lineHeight: 1.5 }}>
              Based on signal confidence. The RM determines whether and how to act.
            </p>
          </div>
        </div>

        {/* ── Prototype relevance factors ─────────────────────────── */}
        <div className="eyebrow" style={{ marginBottom: 10 }}>Prototype relevance factors</div>
        <div className="grid cols-2" style={{ gap: 10, marginBottom: 14 }}>
          {RELEVANCE_FACTORS.map(({ label, score }) => (
            <FactorTile key={label} label={label} score={score} />
          ))}
        </div>

        {/* Disclaimer */}
        <p style={{
          margin: 0,
          fontSize: 12,
          color: 'var(--ink-muted)',
          lineHeight: 1.55,
          borderTop: '1px solid var(--line)',
          paddingTop: 14,
        }}>
          Prototype relevance factors illustrate how portfolio exposure, market context and client
          objectives can be combined to help an RM prioritise attention. These are not AI-generated
          scores and do not constitute investment recommendations.
        </p>
      </div>
    </Card>
  )
}

// ---------------------------------------------------------------------------
// Sub-components — private to this file
// ---------------------------------------------------------------------------

function ReasoningStep({ icon, label, value, chip, children }) {
  return (
    <div style={{ display: 'flex', gap: 14, alignItems: 'flex-start' }}>
      {/* Icon column */}
      <div style={{
        width: 32,
        height: 32,
        borderRadius: '50%',
        background: 'var(--primary-tint)',
        color: 'var(--primary)',
        display: 'grid',
        placeItems: 'center',
        flexShrink: 0,
      }}>
        {icon}
      </div>

      {/* Content column */}
      <div style={{ flex: 1, paddingTop: 4, paddingBottom: 8 }}>
        <div className="eyebrow" style={{ marginBottom: 4 }}>{label}</div>
        {value && !chip && (
          <p style={{ margin: 0, fontSize: 13.5, color: 'var(--ink-soft)', lineHeight: 1.55 }}>
            {value}
          </p>
        )}
        {value && chip && (
          <span style={{
            display: 'inline-block',
            fontSize: 12.5,
            fontWeight: 600,
            color: 'var(--primary)',
            background: 'var(--primary-tint)',
            borderRadius: 30,
            padding: '3px 10px',
            border: '1px solid var(--line)',
          }}>
            {value}
          </span>
        )}
        {children}
      </div>
    </div>
  )
}

function StepConnector() {
  return (
    <div style={{ display: 'flex', alignItems: 'center', gap: 14, padding: '2px 0' }}>
      <div style={{ width: 32, display: 'flex', justifyContent: 'center', flexShrink: 0 }}>
        <ChevronDown size={16} strokeWidth={2} style={{ color: 'var(--gold-soft)' }} />
      </div>
    </div>
  )
}

function FactorTile({ label, score }) {
  return (
    <div style={{
      padding: '13px 15px',
      background: 'var(--surface-2)',
      border: '1px solid var(--line)',
      borderRadius: 'var(--radius-sm)',
    }}>
      <div style={{
        fontSize: 11,
        letterSpacing: '0.08em',
        textTransform: 'uppercase',
        color: 'var(--ink-muted)',
        fontWeight: 600,
        marginBottom: 8,
      }}>
        {label}
      </div>
      <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
        <div style={{
          fontFamily: 'var(--font-serif)',
          fontSize: 22,
          fontWeight: 600,
          letterSpacing: '-0.02em',
          color: 'var(--primary)',
          lineHeight: 1,
        }}>
          {score}
        </div>
        <div style={{ flex: 1, height: 5, borderRadius: 3, background: 'var(--line)', overflow: 'hidden' }}>
          <div style={{ width: `${score}%`, height: '100%', background: 'var(--primary)', borderRadius: 3 }} />
        </div>
      </div>
    </div>
  )
}
